name: Deploy zu Strato

on:
  push:
    branches:
      - main
    paths:
      - 'site/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Hochladen zu Strato per SFTP (nur Unterordner "deployed")
        uses: wangyucode/sftp-upload-action@v3
        with:
          host: ${{ secrets.STRATO_SERVER }}
          username: ${{ secrets.STRATO_USERNAME }}
          password: ${{ secrets.STRATO_PASSWORD }}
          localDir: 'site'
          remoteDir: '/dach/deployed'
          concurrency: 4
