name: Deploy zu Strato

on:
  push:
    branches:
      - main
    paths:
      - 'site/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Hochladen zu Strato per SFTP (nur Unterordner "deployed")
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.STRATO_SERVER }}
          username: ${{ secrets.STRATO_USERNAME }}
          password: ${{ secrets.STRATO_PASSWORD }}
          port: 22
          uploads: |
            ./site/ => ./deployed/
            
